name: openapi_generator_annotations
description: Annotation package for openapi_generator https://pub.dev/packages/openapi_generator.
version: 5.1.0
homepage: https://github.com/ricardoboss/openapi-generator-dart


environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  crypto: '>=3.0.0 <4.0.0'
  meta: '>=1.15.0 <2.0.0'

dev_dependencies:
  test:
  source_gen_test:
  lint:
