name: openapi_generator_cli
description: A dart wrapper around openapi-generator inspired by the node implementation.
version: 5.1.0
homepage: https://github.com/ricardoboss/openapi-generator-dart

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  pedantic:
  test:

executables:
  openapi-generator: main
